### ISSUE TITLE
Issues with async dependencies

### ISSUE THREAD

**Issue by jtfidje** [JasperSui/fastapi-injectable#100]
Hi! I'm having some trouble with my async dependencies. 

The only way I can get `get_injected_obj` to work is by using `loop_manager.set_loop_strategy("background_thread")`.  
Either of the two other options throws exceptions:

- `"current": RuntimeError: This event loop is already running`
- `"isolated:" RuntimeError: Cannot run the event loop while another loop is running`

Now, when using `background_thread` the dependencies are resolved. However, when I try to clean the exit stacks at the end, I get a new stack trace:
```python
try:
    for element in data:
        await my_entrypoint_func(element)
finally:
    await cleanup_all_exit_stacks()
```
```
16:02:43.109 | ERROR   | fastapi_injectable - Failed to cleanup one or more dependency stacks
Traceback (most recent call last):
  File "<venv-path>/lib/python3.12/site-packages/fastapi_injectable/async_exit_stack.py", line 94, in cleanup_all_stacks
    loop_manager.run_in_loop(asyncio.gather(*tasks))  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<venv-path>/lib/python3.12/site-packages/fastapi_injectable/concurrency.py", line 121, in run_in_loop
    return self._wait_with_retries(asyncio.run_coroutine_threadsafe(coro, loop))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/tasks.py", line 937, in run_coroutine_threadsafe
    raise TypeError('A coroutine object is required')
TypeError: A coroutine object is required
```

This is a Prefect-app, meaning Prefect is responsible for creating the initial event loop, if that is of any help.

**EDIT:**
The values of `coro` and `loop` that's passed as parameters in `concurrency.run_in_loop` ( `return self._wait_with_retries(asyncio.run_coroutine_threadsafe(coro, loop))` ) are:
```
Value of    loop    : <_UnixSelectorEventLoop running=True closed=False debug=False>
Value of    coro    : <_GatheringFuture pending>
```

**Comment by JasperSui** [comment]
@jtfidje Thank you for reporting this issue! This was a great catch - the problem occurs because `run_in_loop` was expecting a coroutine object specifically, but `asyncio.gather()` returns a different type of awaitable (a Future).

I've fixed this in PR #101 by modifying `run_in_loop` to properly handle all awaitable types, not just coroutines. This change has been included in the [v0.7.1](https://github.com/JasperSui/fastapi-injectable/releases/tag/v0.7.1) release.

Would you help verify if this release fixes this problem?

Thanks again for the detailed report with the error messages and context - it made identifying and fixing the issue much easier!

**Comment by jtfidje** [comment]
Sweet! Your fix does indeed fix the issue :) Thank you so much for your quick response! 
I still get a warning, but unsure if related. I'll type up another issue in case you have time to look at it! :)
